### ISSUE TITLE
Fix docker-compose

### ISSUE THREAD

**Issue by charlesjliu** [Coding-Coach/coding-coach-api#11]
Currently the Dockerfile for the api container assumes that a `/dist` folder has already been generated. As a result, first time users who clone the repo won't be able to run `docker-compose up -d`. It's critical that anyone be able to run the server locally without error as there will be developers who are focused on the frontend application only.

**Acceptance Criteria**
* A new developer can clone the repo and build and run the database and server using docker-compose
* Update README so that any user can start the server following detailed instructions

**Comment by DillonAd** [comment]
Is the goal of the `docker-compose` to easily build the Docker image for deployment/local testing or just to allow developers to get set up quickly? 

Edit: Re-read the issue again and realized I missed the point. The focus on allowing the front-end devs to do their thing is awesome. Also thank you for clear/concise acceptance criteria!

**Comment by edhaz** [comment]
For future reference: This may be helpful once we've got the CI/CD pipeline running:
https://medium.com/@guillaumejacquart/node-js-docker-workflow-12febcc0eed8

**Comment by charlesjliu** [comment]
@edhaz yeah definitely. I just didn't want to fiddle too much right now, going to open another ticket to improve the pipeline.

**Comment by frederikprijck** [comment]
@charlesjliu  Is this still an issue? I did a fresh check-out of the `development` branch and ran `docker-compose up`. Works fine for me. 

I did some improvements to the docker file (as mentioned in the above article) in https://github.com/Coding-Coach/coding-coach-api/pull/23, but I don't see any issues with using `docker-compose up`.

**Comment by charlesjliu** [comment]
@frederikprijck you're right, I'm closing this one now.
