### ISSUE TITLE
 Forgot Email - Send Reset Link To Email Address

### ISSUE THREAD

**Issue by emmabostian** [Coding-Coach/coding-coach-api#27]
Once the Forgot Password form has been submitted, an email is sent to the user's email address with a reset link.

Email Text: "Uh oh, looks like you forgot your password! Click the link below to reset it and get back to Coding Coach!"

**Comment by JensGryspeert** [comment]
I'll take this one.

**Comment by jabbar86** [comment]
If it is still Open, then I would like to do this.

**Comment by crysfel** [comment]
We are using auth0, no need for this anymore
